<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.lmoesle.miravelo.processautomationexample</groupId>
	<artifactId>process-automation-example-backend-variants</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>miravelo-process-automation-example backend variants</name>
	<description>Aggregator build for independent backend process-engine variants.</description>

	<modules>
		<module>apps/backend</module>
	</modules>
</project>
