@baseUrl = http://localhost:8080
@applicantUserId = 2d88b39b-e7b0-4a3f-b9c6-b3d8e6fbe100
@substituteUserId = f9821988-db4f-4daa-9414-6cc5227f7102

### Create vacation request
POST {{baseUrl}}/api/vacation-requests
Content-Type: application/json
Accept: application/json

{
  "from": "2026-07-01",
  "to": "2026-07-10",
  "applicantUserId": "{{applicantUserId}}",
  "substituteUserId": "{{substituteUserId}}"
}


### Get vacation requests
GET {{baseUrl}}/api/vacation-requests
Content-Type: application/json
Accept: application/json
