// Generated by bpmn-to-code
package de.lmoesle.miravelo.processautomationexample.bpmn;

import io.miragon.bpmn.runtime.BpmnEngine;
import io.miragon.bpmn.runtime.BpmnFlow;
import io.miragon.bpmn.runtime.BpmnRelations;
import io.miragon.bpmn.runtime.ElementId;
import io.miragon.bpmn.runtime.MessageName;
import io.miragon.bpmn.runtime.ProcessId;
import io.miragon.bpmn.runtime.VariableName;
import java.lang.String;
import java.util.List;

public final class VacationApprovalProcessApi {
  public static final ProcessId PROCESS_ID = new ProcessId("vacation_approval");

  public static final BpmnEngine PROCESS_ENGINE = BpmnEngine.CAMUNDA_7;

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  public static final class Elements {
    public static final ElementId ACTIVITY_0_TID_0_X_1 = new ElementId("Activity_0tid0x1");

    public static final ElementId EVENT_SUB_PROCESS_AUTOMATIC_CHECK_RESULT = new ElementId("EventSubProcess_automatic_check_result");

    public static final ElementId EVENT_0_T_9_KNC_8 = new ElementId("Event_0t9knc8");

    public static final ElementId EVENT_1_A_2_Z_938 = new ElementId("Event_1a2z938");

    public static final ElementId EVENT_1_X_1_PZDI = new ElementId("Event_1x1pzdi");

    public static final ElementId EVENT_AUTOMATIC_CHECK_RESULT = new ElementId("Event_automatic_check_result");

    public static final ElementId EVENT_AUTOMATIC_CHECK_RESULT_END = new ElementId("Event_automatic_check_result_end");

    public static final ElementId GATEWAY_01_Y_0_OMZ = new ElementId("Gateway_01y0omz");

    public static final ElementId GATEWAY_18_NQZ_6_R = new ElementId("Gateway_18nqz6r");

    public static final ElementId START_EVENT_1 = new ElementId("StartEvent_1");

    public static final ElementId AUTOMATIC_CHECK = new ElementId("automatic_check");
  }

  /**
   * BPMN message names used to correlate messages to running process instances.
   */
  public static final class Messages {
    public static final MessageName AUTOMATIC_CHECK_RESULT = new MessageName("automatic_check_result");
  }

  /**
   * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
   * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
   */
  public static final class ServiceTasks {
    public static final String AUTOMATIC_CHECK = "automatic_check";
  }

  /**
   * Process variables grouped by the BPMN element that declares them.
   * Direction is encoded in each variable's wrapper type: {@code VariableName.Input}, {@code VariableName.Output}, or {@code VariableName.InOut} when the variable is both read and written by the same element.
   * Consumer APIs that take a specific subtype (for example, a method accepting {@code VariableName.Output}) get compile-time direction enforcement.
   */
  public static final class Variables {
    public static final class AutomaticCheck {
      public static final VariableName.Output GUELTIG = new VariableName.Output("gueltig");

      public static final VariableName.Input URLAUBSANTRAG_ID = new VariableName.Input("urlaubsantragId");
    }
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  public static final class Flows {
    public static final BpmnFlow FLOW_0_BLCZZW = new BpmnFlow("Flow_0blczzw", "Ja", "Gateway_18nqz6r", "Event_1x1pzdi", "${genehmigt == true}", false);

    public static final BpmnFlow FLOW_0_SIRZWJ = new BpmnFlow("Flow_0sirzwj", null, "automatic_check", "Gateway_01y0omz", null, false);

    public static final BpmnFlow FLOW_11_HL_1_GA = new BpmnFlow("Flow_11hl1ga", null, "StartEvent_1", "automatic_check", null, false);

    public static final BpmnFlow FLOW_18_DO_1_VP = new BpmnFlow("Flow_18do1vp", "Nein", "Gateway_01y0omz", "Event_1a2z938", "${gueltig == false}", false);

    public static final BpmnFlow FLOW_1_CYFUD_8 = new BpmnFlow("Flow_1cyfud8", "Nein", "Gateway_18nqz6r", "Event_0t9knc8", "${genehmigt == false}", false);

    public static final BpmnFlow FLOW_1_SA_7_EZG = new BpmnFlow("Flow_1sa7ezg", "Ja", "Gateway_01y0omz", "Activity_0tid0x1", "${gueltig == true}", false);

    public static final BpmnFlow FLOW_1_ST_3_RY_8 = new BpmnFlow("Flow_1st3ry8", null, "Activity_0tid0x1", "Gateway_18nqz6r", null, false);

    public static final BpmnFlow FLOW_AUTOMATIC_CHECK_RESULT_EVENT = new BpmnFlow("Flow_automatic_check_result_event", null, "Event_automatic_check_result", "Event_automatic_check_result_end", null, false);
  }

  /**
   * Per-element graph metadata (previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  public static final class Relations {
    public static final BpmnRelations ACTIVITY_0_TID_0_X_1 = new BpmnRelations("Genehmigung von Vorgesetztem", List.of("Gateway_01y0omz"), List.of("Gateway_18nqz6r"), null, null, List.of());

    public static final BpmnRelations EVENT_SUB_PROCESS_AUTOMATIC_CHECK_RESULT = new BpmnRelations(null, List.of(), List.of(), null, null, List.of());

    public static final BpmnRelations EVENT_0_T_9_KNC_8 = new BpmnRelations("Abgelehnt", List.of("Gateway_18nqz6r"), List.of(), null, null, List.of());

    public static final BpmnRelations EVENT_1_A_2_Z_938 = new BpmnRelations("Abgelehnt", List.of("Gateway_01y0omz"), List.of(), null, null, List.of());

    public static final BpmnRelations EVENT_1_X_1_PZDI = new BpmnRelations("Genehmigt", List.of("Gateway_18nqz6r"), List.of(), null, null, List.of());

    public static final BpmnRelations EVENT_AUTOMATIC_CHECK_RESULT = new BpmnRelations(null, List.of(), List.of("Event_automatic_check_result_end"), "EventSubProcess_automatic_check_result", null, List.of());

    public static final BpmnRelations EVENT_AUTOMATIC_CHECK_RESULT_END = new BpmnRelations(null, List.of("Event_automatic_check_result"), List.of(), "EventSubProcess_automatic_check_result", null, List.of());

    public static final BpmnRelations GATEWAY_01_Y_0_OMZ = new BpmnRelations("Ist der Antrag gülting?", List.of("automatic_check"), List.of("Activity_0tid0x1", "Event_1a2z938"), null, null, List.of());

    public static final BpmnRelations GATEWAY_18_NQZ_6_R = new BpmnRelations("Genehmigt", List.of("Activity_0tid0x1"), List.of("Event_1x1pzdi", "Event_0t9knc8"), null, null, List.of());

    public static final BpmnRelations START_EVENT_1 = new BpmnRelations("Urlaubsantrag stellen", List.of(), List.of("automatic_check"), null, null, List.of());

    public static final BpmnRelations AUTOMATIC_CHECK = new BpmnRelations("Automatisch Prüfung des Antrags", List.of("StartEvent_1"), List.of("Gateway_01y0omz"), null, null, List.of());
  }
}
