/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle User Tasks laden
         * @description Liefert alle fuer den aktuell angemeldeten Benutzer sichtbaren User Tasks. Solange keine Authentifizierung existiert, ist der Benutzer im Controller fest verdrahtet.
         */
        get: operations["getAllTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Task per ID laden
         * @description Liefert einen einzelnen User Task fuer den aktuell angemeldeten Benutzer inklusive Payload anhand seiner technischen ID.
         */
        get: operations["getTaskById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/vorgesetztenentscheidung": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Genehmigung vom Vorgesetzten entscheiden
         * @description Der aktuelle Benutzer entscheidet ueber den sichtbaren User Task und kann optional einen Kommentar fuer die Statushistorie hinterlegen. Beim Abschluss wird die Aufgabe automatisch dem aktuellen Benutzer zugewiesen und danach abgeschlossen. Solange keine Authentifizierung existiert, ist der Benutzer im Controller fest verdrahtet.
         */
        post: operations["entscheideGenehmigungVomVorgesetzten"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/urlaubsantraege": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Urlaubsanträge laden
         * @description Laedt alle Urlaubsantraege fuer den aktuell angemeldeten Benutzer. Solange keine Authentifizierung existiert, ist der Benutzer im Controller fest verdrahtet.
         */
        get: operations["ladeUrlaubsantraege"];
        put?: never;
        /**
         * Urlaubsantrag erstellen
         * @description Erstellt einen neuen Urlaubsantrag, speichert ihn und startet den BPMN-Genehmigungsprozess.
         */
        post: operations["erstelleUrlaubsantrag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BenutzerDto: {
            /**
             * @description E-Mail-Adresse des Benutzers.
             * @example ada.lovelace@example.com
             */
            email?: string;
            /**
             * @description Anzeigename des Benutzers.
             * @example Ada Lovelace
             */
            name?: string;
        };
        ProblemDetail: {
            detail?: string;
            /** Format: uri */
            instance?: string;
            properties?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            status?: number;
            title?: string;
            /** Format: uri */
            type?: string;
        };
        UrlaubsantragDto: {
            /** @description Aufgeloester Antragsteller. */
            antragsteller?: components["schemas"]["BenutzerDto"];
            /**
             * Format: date
             * @description Endedatum des beantragten Urlaubszeitraums.
             * @example 2026-07-10
             */
            bis?: string;
            /**
             * Format: uuid
             * @description Technische ID des Urlaubsantrags.
             * @example c7a6939b-a97b-4445-bd66-4a0f98781899
             */
            id?: string;
            /**
             * @description Aktueller Status des Urlaubsantrags.
             * @example ANTRAG_GESTELLT
             * @enum {string}
             */
            status?: UrlaubsantragDtoStatus;
            /** @description Chronologische Historie der erfassten Urlaubsantragsstatus. */
            statusHistorie?: components["schemas"]["UrlaubsantragStatusHistorieneintragDto"][];
            /** @description Aufgeloeste Vertretung waehrend des Urlaubszeitraums. */
            vertretung?: components["schemas"]["BenutzerDto"];
            /**
             * Format: date
             * @description Startdatum des beantragten Urlaubszeitraums.
             * @example 2026-07-01
             */
            von?: string;
            /** @description Zugeordneter Vorgesetzter fuer die Pruefung des Urlaubsantrags. */
            vorgesetzter?: components["schemas"]["BenutzerDto"];
        };
        UrlaubsantragErstellenDto: {
            /**
             * Format: uuid
             * @description Benutzer-ID des Antragstellers.
             * @example 2d88b39b-e7b0-4a3f-b9c6-b3d8e6fbe100
             */
            antragstellerId: string;
            /**
             * Format: date
             * @description Endedatum des beantragten Urlaubszeitraums.
             * @example 2026-07-10
             */
            bis: string;
            /**
             * Format: uuid
             * @description Optionale Benutzer-ID der Vertretung waehrend des Urlaubszeitraums.
             * @example f9821988-db4f-4daa-9414-6cc5227f7102
             */
            vertretungId?: string;
            /**
             * Format: date
             * @description Startdatum des beantragten Urlaubszeitraums.
             * @example 2026-07-01
             */
            von: string;
            zeitraumGueltig?: boolean;
        };
        UrlaubsantragStatusHistorieneintragDto: {
            /** @description Optionaler Kommentar zur Statusaenderung. */
            kommentar?: string;
            /**
             * @description Status, der fuer den Urlaubsantrag erfasst wurde.
             * @example ANTRAG_GESTELLT
             * @enum {string}
             */
            status?: UrlaubsantragStatusHistorieneintragDtoStatus;
        };
        UserTaskDto: {
            /** @description Aufgeloester Bearbeiter aus dem assignee des User Tasks. */
            bearbeiter?: components["schemas"]["BenutzerDto"];
            /** @description Aufgeloeste Nutzer aus der Variable candidateUsers. */
            candidateUsers?: components["schemas"]["BenutzerDto"][];
            /**
             * @description Technische ID des User Tasks.
             * @example approve-vacation-1
             */
            taskId?: string;
            /** @description Zugehoeriger Urlaubsantrag, falls im Payload eine urlaubsantragId enthalten ist. */
            urlaubsantrag?: components["schemas"]["UrlaubsantragDto"];
        };
        VorgesetztenentscheidungDto: {
            /**
             * @description Entscheidung des Vorgesetzten. `true` genehmigt den Antrag, `false` lehnt ihn ab.
             * @example true
             */
            genehmigt: boolean;
            /**
             * @description Optionaler Kommentar des Vorgesetzten, der in der Statushistorie sichtbar wird.
             * @example Vertretung ist organisiert.
             */
            kommentar?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaBenutzerDto = components['schemas']['BenutzerDto'];
export type SchemaProblemDetail = components['schemas']['ProblemDetail'];
export type SchemaUrlaubsantragDto = components['schemas']['UrlaubsantragDto'];
export type SchemaUrlaubsantragErstellenDto = components['schemas']['UrlaubsantragErstellenDto'];
export type SchemaUrlaubsantragStatusHistorieneintragDto = components['schemas']['UrlaubsantragStatusHistorieneintragDto'];
export type SchemaUserTaskDto = components['schemas']['UserTaskDto'];
export type SchemaVorgesetztenentscheidungDto = components['schemas']['VorgesetztenentscheidungDto'];
export type $defs = Record<string, never>;
export interface operations {
    getAllTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User Tasks erfolgreich geladen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTaskDto"][];
                };
            };
        };
    };
    getTaskById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User Task erfolgreich geladen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserTaskDto"];
                };
            };
            /** @description Kein User Task mit der angegebenen ID gefunden. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserTaskDto"];
                };
            };
        };
    };
    entscheideGenehmigungVomVorgesetzten: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VorgesetztenentscheidungDto"];
            };
        };
        responses: {
            /** @description Vorgesetztenentscheidung erfolgreich verarbeitet. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ungueltige Anfrage, zum Beispiel bei fehlender Entscheidung oder ungueltigem Kommentar. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Der aktuelle Benutzer darf die Aufgabe nicht abschliessen. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Kein User Task mit der angegebenen ID gefunden. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    ladeUrlaubsantraege: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Urlaubsantraege erfolgreich geladen. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlaubsantragDto"][];
                };
            };
        };
    };
    erstelleUrlaubsantrag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlaubsantragErstellenDto"];
            };
        };
        responses: {
            /** @description Urlaubsantrag erfolgreich erstellt. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlaubsantragDto"];
                };
            };
            /** @description Ungueltige Anfrage, zum Beispiel wenn `von` nach `bis` liegt. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
export enum UrlaubsantragDtoStatus {
    ANTRAG_GESTELLT = "ANTRAG_GESTELLT",
    AUTOMATISCHE_PRUEFUNG = "AUTOMATISCHE_PRUEFUNG",
    VORGESETZTEN_PRUEFUNG = "VORGESETZTEN_PRUEFUNG",
    ABGELEHNT = "ABGELEHNT",
    GENEHMIGT = "GENEHMIGT"
}
export enum UrlaubsantragStatusHistorieneintragDtoStatus {
    ANTRAG_GESTELLT = "ANTRAG_GESTELLT",
    AUTOMATISCHE_PRUEFUNG = "AUTOMATISCHE_PRUEFUNG",
    VORGESETZTEN_PRUEFUNG = "VORGESETZTEN_PRUEFUNG",
    ABGELEHNT = "ABGELEHNT",
    GENEHMIGT = "GENEHMIGT"
}
