// Generated by bpmn-to-code
package de.lmoesle.processautomationexample.bpmn;

import java.lang.String;

public final class VacationApprovalProcessApi {
  public static final String PROCESS_ID = "vacation_approval";

  public static final String PROCESS_ENGINE = "CAMUNDA_7";

  public static final class Elements {
    public static final String ACTIVITY_0_TID_0_X_1 = "Activity_0tid0x1";

    public static final String EVENT_SUB_PROCESS_AUTOMATIC_CHECK_RESULT = "EventSubProcess_automatic_check_result";

    public static final String EVENT_0_T_9_KNC_8 = "Event_0t9knc8";

    public static final String EVENT_1_A_2_Z_938 = "Event_1a2z938";

    public static final String EVENT_1_X_1_PZDI = "Event_1x1pzdi";

    public static final String EVENT_AUTOMATIC_CHECK_RESULT = "Event_automatic_check_result";

    public static final String EVENT_AUTOMATIC_CHECK_RESULT_END = "Event_automatic_check_result_end";

    public static final String GATEWAY_01_Y_0_OMZ = "Gateway_01y0omz";

    public static final String GATEWAY_18_NQZ_6_R = "Gateway_18nqz6r";

    public static final String START_EVENT_1 = "StartEvent_1";

    public static final String AUTOMATIC_CHECK = "automatic_check";
  }

  public static final class Messages {
    public static final String AUTOMATIC_CHECK_RESULT = "automatic_check_result";
  }

  public static final class TaskTypes {
    public static final String AUTOMATIC_CHECK = "automatic_check";
  }

  public static final class Variables {
    public static final String GUELTIG = "gueltig";

    public static final String URLAUBSANTRAG_ID = "urlaubsantragId";
  }
}
