spring:
  application:
    name: process-automation-example
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:vacation-approval}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  flyway:
    enabled: true
    locations: "classpath:db/migration/schema"

camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_ADMIN_USER:admin}
      password: ${CAMUNDA_ADMIN_PASSWORD:admin}
      first-name: ${CAMUNDA_ADMIN_FIRST_NAME:Admin}
      last-name: ${CAMUNDA_ADMIN_LAST_NAME:Admin}

dev:
  bpm-crafters:
    process-api:
      worker:
        deployment:
          enabled: true
          bpmnResourcePattern: "classpath*:/bpmn/*.bpmn"
      adapter:
        c7embedded:
          enabled: true
          service-tasks:
            delivery-strategy: embedded_scheduled
            worker-id: embedded-worker
            lock-time-in-seconds: 10
            execute-initial-pull-on-startup: true
            schedule-delivery-fixed-rate-in-seconds: 10
            retries: 3
            max-task-count: 100
            retry-timeout-in-seconds: 30
          user-tasks:
            delivery-strategy: embedded_scheduled
            execute-initial-pull-on-startup: true
            schedule-delivery-fixed-rate-in-seconds: 10

de.lmoesle:
  processautomationexample:
    mail:
      from-address: ${MAIL_FROM:no-reply@process-automation-example.local}
      standard-template: classpath:mail/standard-benachrichtigung.mail.html
      frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
